#!/usr/bin/env bash

main() {
  set -euo pipefail
  if [[ -n "${DEBUG:-}" ]]; then set -x; fi
  if [[ -n "${TRACE:-}" ]]; then set -xv; fi

  "${0%/*}/../libexec/run-with-docker.sh" bash -c \
    "pacman-key --init && pacman-key --populate archlinux \
    && $(dirname "$0")/build"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@" || exit 99
fi
